config/routes.rb
Rails.application.routes.draw do
  resources :alledit, only: [:new, :create]
  resources :companies, only: [:index, :create, :show]
  root to: "top#index"

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "100x200>", thumb: "100x100>"}
  validates_attachment_content_type :avatar, content_type: %w(image/jpeg image/jpg image/png)
end

app/controllers/alledit_controller.rb
class AlleditController < ApplicationController
  def new
    @company = Company.new
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @company = Company.order("id DESC")
  end

  def create
    Company.create(create_params)
  end

  def create_params
    params.require(:company).permit(:name, :avatar, :jikyu, :location, :detail)
  end

  def show
    @company = Company.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/alledit_helper.rb
module AlleditHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/alledit/new.html.erb
<div class="row-fluid">
  <div class="span4 well">
    <%= form_for (@company) do |f| %>
        <fieldset>

          <%= f.label :"店名"  %>
          <%= f.text_field :name %>

          <%= f.label :"写真" %>
          <%= f.file_field :avatar %>

          <%= f.label :"時給" %>
          <%= f.text_field :jikyu %>

          <%= f.label :"場所" %>
          <%= f.text_field :location %>

          <%= f.label :"詳細" %>
          <%= f.text_field :detail %>

          <%= f.submit "送信", :class => 'btn btn-primary withripple' %>
    <% end %>
   </div>
</div>

app/views/companies/_company.html.erb
<%= link_to company_path(company.id) do %>
  <div class ="company clearfix">
    <div class = "name"><%= company.name %></div>
    <div class = "detail company_avatar"><img src ="<%= company.avatar.url(:thumb) %>"></div>
    <div class = "detail">時給<br><%= company.jikyu %><br>場所<br><%= company.location %></div>
  </div>
<% end %>

app/views/companies/create.html.erb
新しいバイト先を登録しました

app/views/companies/index.html.erb
<div class ="clearfix">
  <form class="navbar-form pull-left" role="search">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Search">
        <div class="input-group-btn">
          <button type="submit" class="btn btn-default">
          <span class="glyphicon glyphicon-search"></span>
          </button>
        </div>
      </div>
  </form>
</div>
<%= render partial: "companies/company", collection: @company %>

app/views/companies/show.html.erb
<!-- 
    data-ride="carousel"を入れると自動的にスライドが開始される
-->

<div id="carousel_sample" class="carousel slide" data-ride="carousel">

    <!-- 中央に表示される丸いボタン -->
  <ol class="carousel-indicators">

    <!-- 
        Carouselのid名を合わせる、スライダーの数だけ用意する
            data-slide-toで何番目のスライドへ移動するか指定する、0から始めるので１つめのスライドなら0を指定
     -->
    <li data-target="#carousel_sample" data-slide-to="0" class="active"></li>
    <li data-target="#carousel_sample" data-slide-to="1" class=""></li>
    <li data-target="#carousel_sample" data-slide-to="2" class=""></li>

  </ol>

  <!-- ここからCarouselの中身 -->
  <div class="carousel-inner">

    <!-- item = １ページ、activeを入れたところが最初に表示される -->
    <div class="item active">
      <!-- <img  src="../../app/assets/images/sano.jpg"> -->
      <%= image_tag 'sano.jpg', data: {src: "holder.js/900x500/auto/#777:#555/text:First slide"}, alt: "First slide" %>
    </div>
    <div class="item">
      <%= image_tag @company.avatar, data: {src: "holder.js/900x500/auto/#666:#444/text:Second slide"}, alt: "Second slide" %>
      <!-- <img data-src="holder.js/900x500/auto/#666:#444/text:Second slide" alt="Second slide" src="../../assets/images/さのひな２.jpg"> -->
    </div>
    <div class="item">
      <img data-src="holder.js/900x500/auto/#555:#333/text:Third slide" alt="Third slide" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI5MDAiIGhlaWdodD0iNTAwIj48cmVjdCB3aWR0aD0iOTAwIiBoZWlnaHQ9IjUwMCIgZmlsbD0iIzU1NSIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjQ1MCIgeT0iMjUwIiBzdHlsZT0iZmlsbDojMzMzO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjU2cHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+VGhpcmQgc2xpZGU8L3RleHQ+PC9zdmc+">
    </div>

  </div>

  <!-- ページ送りボタン、ここもCarouselのid名を合わせる -->
  <a class="left carousel-control" href="#carousel_sample" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel_sample" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>



<table border="1" width="500" height="200s" cellspacing="2" cellpadding="2" bgcolor="#f0f8ff">
<tr align="center">
<td>店名</td>
<td><%= @company.name %></td>
</tr>
<tr align="center">
<td>時給</td>
<td><%= @company.jikyu %></td>
</tr>
<tr align="center">
<td>場所</td>
<td><%= @company.location %></td>
</tr>
<tr align="center">
<td>詳細</td>
<td><%= @company.detail %></td>
</tr>
</table>

  <p>ここで働く</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KyujinCampus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>
 
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'アルバイトを探す', companies_path %><span class="sr-only">(current)</span></li>
        <li><a href="#">祝い金申請</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">運営会社 <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">会社概要</a></li>
            <li><a href="#">運営メンバー</a></li>
            <li><a href="#">お問い合わせ</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to '編集', new_alledit_path %></li>
        <li><a href="#">求人campus</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>